# Generated by Django 2.2.2 on 2019-06-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
