# Generated by Django 2.2.2 on 2019-06-29 18:20

from django.db import migrations

def insert_todos(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Todo = apps.get_model('todos', 'Todo')

    user1 = User.objects.get(pk=1)

    todo1 = Todo.objects.create(
        title="Zrobic1",
        user=user1
    )
    todo2 = Todo.objects.create(
        title="Zrobic2",
        user=user1
    )
    todo3 = Todo.objects.create(
        title="Zrobic3",
        user=user1
    )

class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_todos),
    ]
