# Generated by Django 2.2.2 on 2019-06-29 17:56

from django.db import migrations
from django.contrib.auth.hashers import make_password

def insert_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    user1 = User.objects.create(
        username="Admin",
        email="admin@admin.pl"
    )
    user1.password = make_password('admin123')
    user1.save()

    user2 = User.objects.create(
        username="User",
        email="user@user.pl"
    )
    user2.password = make_password('user123')
    user2.save()

    user3 = User.objects.create(
        username="Test",
        email="test@test.pl"
    )
    user3.password = make_password('test123')
    user3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_users),
    ]
